# Generated by Django 4.1.6 on 2023-02-01 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("natural", "Natural"), ("juridica", "Jurídica")],
                        max_length=10,
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.MaxLengthValidator(10),
                            django.core.validators.RegexValidator("^\\d+$"),
                        ],
                    ),
                ),
                (
                    "dv",
                    models.CharField(
                        max_length=1,
                        validators=[
                            django.core.validators.MaxLengthValidator(1),
                            django.core.validators.RegexValidator("^\\d+$"),
                        ],
                    ),
                ),
                ("direccion", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.MaxLengthValidator(10),
                            django.core.validators.RegexValidator("^\\d+$"),
                        ],
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.MaxLengthValidator(10),
                            django.core.validators.RegexValidator("^\\d+$"),
                        ],
                    ),
                ),
                ("departamento", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=100)),
            ],
        ),
    ]
