# Generated by Django 4.1.6 on 2023-02-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_AYR_Control", "0003_funcionariocontacto"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionariocontacto",
            name="area",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="funcionariocontacto",
            name="cargo",
            field=models.CharField(default="", max_length=255),
        ),
    ]
