# Generated by Django 4.1.6 on 2023-02-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("APP_AYR_Control", "0004_funcionariocontacto_area_funcionariocontacto_cargo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulacionCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "monto_solicitado",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "tasa_efectiva_anual",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("forma_pago", models.CharField(max_length=20)),
                ("tasa_efectiva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("numero_cuotas", models.PositiveSmallIntegerField()),
                ("primera_cuota", models.DateField()),
                ("otros_cargos", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APP_AYR_Control.cliente",
                    ),
                ),
                (
                    "funcionario_de_contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APP_AYR_Control.funcionariocontacto",
                    ),
                ),
                (
                    "representante_legal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APP_AYR_Control.representantelegal",
                    ),
                ),
            ],
        ),
    ]
